# Generated by Django 3.0.7 on 2020-06-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_auto_20200623_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
